# Generated by Django 5.2.8 on 2026-03-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='periodo',
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.PositiveSmallIntegerField(default=1, help_text='Duración en meses (1-12)'),
        ),
    ]
