# Generated by Django 5.2.8 on 2026-03-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_curso_periodo_curso_duracion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
