# Generated by Django 5.2.8 on 2026-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField(default=0, verbose_name='Parcial 1')),
                ('nota2', models.FloatField(default=0, verbose_name='Parcial 2')),
                ('nota3', models.FloatField(default=0, verbose_name='Examen Final')),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
