# Generated by Django 5.2.8 on 2026-03-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='cursos.curso'),
        ),
    ]
