# Generated by Django 5.2.8 on 2026-03-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota2',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota3',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='notas',
            field=models.JSONField(default=list, verbose_name='Notas'),
        ),
    ]
